"""criando tabela formas_pagamento

Revision ID: 04601448c36d
Revises: 4fcb6abf19f5
Create Date: 2026-02-01 07:40:55.290583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04601448c36d'
down_revision = '4fcb6abf19f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forma_pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('papelaria_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['papelaria_id'], ['papelaria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forma_pagamento')
    # ### end Alembic commands ###
