"""inclusao despesas

Revision ID: 0f3fe2b17fd7
Revises: b804eb54b263
Create Date: 2026-02-01 18:45:15.524271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f3fe2b17fd7'
down_revision = 'b804eb54b263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('despesa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('papelaria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], name=op.f('fk_despesa_categoria_id_categoria')),
    sa.ForeignKeyConstraint(['papelaria_id'], ['papelaria.id'], name=op.f('fk_despesa_papelaria_id_papelaria')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_despesa'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('despesa')
    # ### end Alembic commands ###
