"""att papelaria class

Revision ID: 20ba7657f10a
Revises: 0f3fe2b17fd7
Create Date: 2026-02-02 14:07:39.204370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20ba7657f10a'
down_revision = '0f3fe2b17fd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papelaria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnpj_cpf', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('site', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('telefones', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('chave_pix', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('logo_path', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('cep', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('logradouro', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('numero', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('bairro', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cidade', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('complemento', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papelaria', schema=None) as batch_op:
        batch_op.drop_column('complemento')
        batch_op.drop_column('estado')
        batch_op.drop_column('cidade')
        batch_op.drop_column('bairro')
        batch_op.drop_column('numero')
        batch_op.drop_column('logradouro')
        batch_op.drop_column('cep')
        batch_op.drop_column('logo_path')
        batch_op.drop_column('chave_pix')
        batch_op.drop_column('telefones')
        batch_op.drop_column('site')
        batch_op.drop_column('email')
        batch_op.drop_column('cnpj_cpf')

    # ### end Alembic commands ###
