"""Migracao inicial saas

Revision ID: 400451ff31c2
Revises: 
Create Date: 2026-02-03 10:37:36.015333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400451ff31c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papelaria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=100), nullable=False),
    sa.Column('cnpj_cpf', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('site', sa.String(length=100), nullable=True),
    sa.Column('telefones', sa.String(length=100), nullable=True),
    sa.Column('chave_pix', sa.String(length=100), nullable=True),
    sa.Column('logo_path', sa.String(length=200), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('logradouro', sa.String(length=150), nullable=True),
    sa.Column('numero', sa.String(length=10), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_papelaria'))
    )
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('papelaria_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['papelaria_id'], ['papelaria.id'], name=op.f('fk_categoria_papelaria_id_papelaria')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categoria'))
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('papelaria_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('whatsapp', sa.String(length=20), nullable=False),
    sa.Column('logradouro', sa.String(length=150), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.ForeignKeyConstraint(['papelaria_id'], ['papelaria.id'], name=op.f('fk_cliente_papelaria_id_papelaria')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cliente'))
    )
    op.create_table('forma_pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('papelaria_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['papelaria_id'], ['papelaria.id'], name=op.f('fk_forma_pagamento_papelaria_id_papelaria')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forma_pagamento'))
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('papelaria_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['papelaria_id'], ['papelaria.id'], name=op.f('fk_usuario_papelaria_id_papelaria')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario')),
    sa.UniqueConstraint('username', name=op.f('uq_usuario_username'))
    )
    op.create_table('despesa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('papelaria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], name=op.f('fk_despesa_categoria_id_categoria')),
    sa.ForeignKeyConstraint(['papelaria_id'], ['papelaria.id'], name=op.f('fk_despesa_papelaria_id_papelaria')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_despesa'))
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('papelaria_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('preco_custo', sa.Float(), nullable=True),
    sa.Column('preco_venda', sa.Float(), nullable=False),
    sa.Column('estoque_atual', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], name=op.f('fk_produto_categoria_id_categoria')),
    sa.ForeignKeyConstraint(['papelaria_id'], ['papelaria.id'], name=op.f('fk_produto_papelaria_id_papelaria')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_produto'))
    )
    op.create_table('servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=False),
    sa.Column('custo', sa.Float(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('papelaria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], name=op.f('fk_servico_categoria_id_categoria')),
    sa.ForeignKeyConstraint(['papelaria_id'], ['papelaria.id'], name=op.f('fk_servico_papelaria_id_papelaria')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_servico'))
    )
    op.create_table('movimentacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('papelaria_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=20), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('servico_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('venda_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_movimentacao_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['papelaria_id'], ['papelaria.id'], name=op.f('fk_movimentacao_papelaria_id_papelaria')),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], name=op.f('fk_movimentacao_produto_id_produto')),
    sa.ForeignKeyConstraint(['servico_id'], ['servico.id'], name=op.f('fk_movimentacao_servico_id_servico')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movimentacao'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimentacao')
    op.drop_table('servico')
    op.drop_table('produto')
    op.drop_table('despesa')
    op.drop_table('usuario')
    op.drop_table('forma_pagamento')
    op.drop_table('cliente')
    op.drop_table('categoria')
    op.drop_table('papelaria')
    # ### end Alembic commands ###
