"""adicionado preco_custo ao produto

Revision ID: 4fcb6abf19f5
Revises: 04fc85615f6c
Create Date: 2026-01-30 21:45:22.628205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fcb6abf19f5'
down_revision = '04fc85615f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preco_custo', sa.Float(), nullable=True))
        batch_op.alter_column('preco_venda',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.alter_column('preco_venda',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
        batch_op.drop_column('preco_custo')

    # ### end Alembic commands ###
