"""empty message

Revision ID: 56b41b2507c5
Revises: e8c11148a66c
Create Date: 2026-01-30 10:47:38.704880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56b41b2507c5'
down_revision = 'e8c11148a66c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimentacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forma_pagamento', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('quantidade', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimentacao', schema=None) as batch_op:
        batch_op.drop_column('quantidade')
        batch_op.drop_column('forma_pagamento')

    # ### end Alembic commands ###
