"""add venda_id

Revision ID: b804eb54b263
Revises: e17a0fe5869e
Create Date: 2026-02-01 12:35:21.765964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b804eb54b263'
down_revision = 'e17a0fe5869e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimentacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venda_id', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimentacao', schema=None) as batch_op:
        batch_op.drop_column('venda_id')

    # ### end Alembic commands ###
